---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: ${nameSpace}
data:
  clusterType: "macbook"
  mgmtClusterName: ww-jlai-macbook
  dnsSuffix: kubernetes.docker.internal
  clusterIP: 10.102.131.35
  scmType: github
  GitHubOrg: ww-gitops
  GitHubRepo: justinlai-ww-macbook
  awsAccountId: ac-none
  prefixName: ww-jlai
  awsRegion: us-east-1
  awsTagCreator: justin.lai@weave.works
  awsTagCustomer: weaveworks-cx
  awsTagProjectGid: "20276"
  userEmail: justin.lai@weave.works
  vault_url: https://vault.kubernetes.docker.internal
  commitUser: jwlai
  awsKeyPairName: jwlai
  sshPubKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0rYOyFw4Y8uyMmXnGOcS/6HPSTk+LrifxMPJ4ebnvEx+UDGZ7Tg2Xtf1wwMV1CE9m3j8QoxNZQ0nzmO/bIODkvgkN30pQbHbgA2diGcEse5ov/d5371PQd53tZz2p5AQscncfEsDHb2JtVXy6EqEdN9349YnLbRsNvuCKDzxUH5XruUB27wd1ri40n+QEXOXDGYgfiRKqk0GSC7jaBSYCUzFnapBNQ7f/NRG0mAJboHci0MCJFRGN3ml2TjXUKtp+A+6ppJ+5UXittF2wIx0fkFcB+B2z1TXJQ17368C2+VE7blBhAKYasZt+q8iT8zSnX9agkaI8YeC7NsCRJNhX
  capi: 
