---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
- wge.yaml
configMapGenerator:
- name: local-ca
  namespace: flux-system
  files:
  - ../../../resources/CA.cer
  options:
    disableNameSuffixHash: true
