"connectors":
- "config":
    "baseURL": "https://github.com"
    "clientID": "$GITHUB_CLIENT_ID"
    "clientSecret": "$GITHUB_CLIENT_SECRET"
    "groups":
    - "$GITHUB_AUTH_ORG"
    "redirectURI": "https://dex.kubernetes.docker.internal/callback"
  "id": "github"
  "name": "GitHub"
  "type": "github"
"issuer": "https://dex.kubernetes.docker.internal"
"oauth2":
  "skipApprovalScreen": true
"staticClients":
- "id": "wge"
  "name": "Weave Gitops Enterprise"
  "redirectURIs":
  - "https://wge.kubernetes.docker.internal/oauth2/callback"
  "secret": "$WGE_DEX_CLIENT_SECRET"
- "id": "vault"
  "name": "Vault"
  "redirectURIs":
  - "https://vault.kubernetes.docker.internal/ui/vault/auth/oidc/oidc/callback"
  - "http://localhost:8250/oidc/callback"
  "secret": "$VAULT_DEX_CLIENT_SECRET"
"storage":
  "type": "memory"
"web":
  "http": "0.0.0.0:5556"