clusters: 
- name: ${wge_cluster_name}
  cluster:
    certificate-authority-data: ${cert}
    server: ${endpoint}
current-context: ${wge_cluster_name}
contexts: 
- name: ${wge_cluster_name}
  context:
    cluster: ${wge_cluster_name}
    user: ${wge_cluster_name}
users: 
- name: ${wge_cluster_name}
  user:
    token: ${token}
