apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all
subjects:
  - kind: User
    name: wge-admin
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: ${userEmail}
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: ww-gitops:admin # Github group
    apiGroup: rbac.authorization.k8s.io
