---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${resourceName}-${clusterName}
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ${resourceName}-${clusterName}-kubeconfig
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ${secret_name}
