apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kind-u2-k1-gitops-kubeconfig
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./leaf-clusters/wge/kubeconfig
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
    substitute:
      clusterName: k1
      resourceName: kind-u2
      secret_name: kind-u2-k1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  annotations:
    templates.weave.works/create-request: ""
  name: kind-u2-k1-gitops-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: kind-u2-k1-gitops-kubeconfig
  interval: 1m0s
  path: ./leaf-clusters/wge/gitops-cluster
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
    substitute:
      clusterName: k1
      resourceName: kind-u2
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 1m
