---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
- ghcr.yaml
- repository.yaml
- release.yaml
configMapGenerator:
- name: local-ca
  namespace: dex
  files:
  - ../../../resources/CA.cer
  options:
    disableNameSuffixHash: true
