---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-config
  namespace: dex
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: dex-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dex-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wge-oidc-auth
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: wge-oidc-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: wge-oidc-auth
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-enterprise-credentials
  namespace: flux-system
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: wge-entitlement
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: weave-gitops-enterprise-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-user-auth
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cluster-user-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: wge-admin-auth
