apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200 # https://vault.${dnsSuffix} 
      path: secrets
      version: v2
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "vault"
          key: "vault_token"
