apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitopssets
  namespace: ${templateNamespace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitopssets-role
  namespace: ${templateNamespace}
rules:
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitopssets-role-binding
  namespace: ${templateNamespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitopssets-role
subjects:
- kind: ServiceAccount
  name: gitopssets
  namespace: ${templateNamespace}