---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ${appName}
  namespace: ${templateNamespace}
spec:
  interval: 1m0s
  ref:
    ${appRefType}: ${appRefValue}
  url: ssh://git@github.com/ww-gitops/${appName}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ${appName}
  namespace: flux-system
spec:
  interval: 1m0s
  path: ${appPath}
  prune: true
  sourceRef:
    kind: GitRepository
    name: ${appName}

