apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 1m0s
  timeout: 5m
  values:
    global:
      enabled: true
    csi:
      enabled: true
    injector:
      enabled: true
    server:
      enabled: true
      dataStorage:
        storageClass: hostpath
      serviceAccount:
        name: vault
      standalone:
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "file" {
            path = "/vault/data"
          }
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: local-ca-issuer
        tls:
          - secretName: vault-tls
            hosts:
              - vault.${dnsSuffix}
        hosts:
          - host: vault.${dnsSuffix}
  postRenderers:
    - kustomize:
        patches:
        - target:
            kind: Pod
            name: vault-0
          patch: |-
            - op: add
              path: /spec/hostAliases
              value:
                - ip: ${clusterIP}
                  hostnames:
                  - "dex.${dnsSuffix}"
                  - "vault.${dnsSuffix}"

            - op: add
              path: /spec/volumes/-
              value:
                name: local-ca
                configMap:
                  name: local-ca

            - op: add
              path: /spec/containers/0/volumeMounts/-
              value:
                name: local-ca
                mountPath: /etc/ssl/certs/local-ca.pem
                subPath: CA.cer
                readOnly: false